backend:
  name: github
  repo: vuesd/website # Path to your GitHub repository

media_folder: "public/static/uploads" # Media files will be stored in the repo under public/static/uploads
public_folder: "/static/uploads" # The src attribute for uploaded media will begin with /static/uploads
collections:
  - label: "Pages" # Used in the UI
    name: "pages" # Used in routes, e.g., /admin/collections/resource
    files:
      - label: "Resources"
        name: "resources"
        file: "src/content/resources.md"
        fields:
          - label: Content
            name: content
            widget: markdown
  - label: Companies
    name: companies
    folder: "src/content/companies"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Website", name: "url", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
